language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpcs -np --colors
  - vendor/bin/phpstan analyse --no-interaction

