name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  call-workflow-ci-php-general:
    name: General
    uses: factorio-item-browser/common/.github/workflows/ci-php-general.yaml@v1
